apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deployment-v1
  labels:
    app: k8s-demo-app-v1

spec:
  replicas: 4

  selector:
    matchLabels:
      app: k8s-demo-v1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: k8s-demo-v1

    spec:
      containers:
      - name: k8s-demo
        image: sheltz/sprint_3_presentation:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3


        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30
          periodSeconds: 5

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"